"""add notifications settings to user

Revision ID: 3193bafd60f0
Revises: 4cc14a1df9f8
Create Date: 2026-06-17 17:08:42.113120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3193bafd60f0'
down_revision = '4cc14a1df9f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 🆕 Добавляем server_default=True, чтобы существующие пользователи получили значение по умолчанию
    op.add_column('users', sa.Column('notify_responses', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('notify_messages', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_messages')
    op.drop_column('users', 'notify_responses')
    # ### end Alembic commands ###