"""add is_premium to user

Revision ID: df6e9e2ef62e
Revises: 011ab2575801
Create Date: 2026-06-21 15:05:11.673905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6e9e2ef62e'
down_revision = '011ab2575801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###