// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIxLEiJIfEVK3_oDe8v29NdzXzayYAGrc',
    appId: '1:451760169474:web:2811f831df77afa3a93d1b',
    messagingSenderId: '451760169474',
    projectId: 'tet-a-tet-app',
    authDomain: 'tet-a-tet-app.firebaseapp.com',
    storageBucket: 'tet-a-tet-app.firebasestorage.app',
    measurementId: 'G-S07VLHS5XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdT5srVxQCe6TOKPEKSI0opAMeBqdUdBc',
    appId: '1:451760169474:android:469f17b233b3298ca93d1b',
    messagingSenderId: '451760169474',
    projectId: 'tet-a-tet-app',
    storageBucket: 'tet-a-tet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNUhlX1-ntUElaajaQvSYHEHFKrhLcxk',
    appId: '1:451760169474:ios:198472e43f094a8ea93d1b',
    messagingSenderId: '451760169474',
    projectId: 'tet-a-tet-app',
    storageBucket: 'tet-a-tet-app.firebasestorage.app',
    iosBundleId: 'com.example.tetATetApp',
  );
}
